name: CI

on:
  schedule:
  - cron: "11 11 * * 6"

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: crypto-bot

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1

      - name: Install Dependencies
        run: npm install

      - name: Run Bot
        env:
          API_KEY: ${{secrets.API_KEY}}
          API_SECRET: ${{secrets.API_SECRET}}
          PASSPHRASE: ${{secrets.PASSPHRASE}}
        run: npm start
